[world]
kind = "Contract"
class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
original_class_hash = "0x799bc4e9da10bfb3dd88e6f223c9cfbf7745435cd14f5d69675ea448e578cd"
abi = "abis/deployments/dojo_world_world.json"
address = "0x43c803d263b1e5ce7fac9d0b883476b0e656a5180d9ea9b845585cb4c20f182"
transaction_hash = "0x7db352d4ec29ba9fe9cc002fa7a40b81b6599265900ef67db17cdb627d0928"
block_number = 3
seed = "blobbar"
name = "dojo::world::world"

[base]
kind = "Class"
class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
original_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x9f7dbda0ced84f68c14ee07b753f1b019651e7c0d26838f65553b6061aeb92"
class_hash = "0x13842c0df8c8d06577671271d9d1e9d1545fe04bee87a5e6cb087b89379aacf"
original_class_hash = "0x13842c0df8c8d06577671271d9d1e9d1545fe04bee87a5e6cb087b89379aacf"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/blobbar_blobert_descriptor_Descriptor.json"
reads = []
writes = []
computed = []
name = "blobbar::blobert::descriptor::Descriptor"

[[contracts]]
kind = "DojoContract"
address = "0x6793d351f9e180f451019db2b30ad8d11bb48c4fe6c31f038097f50224190f7"
class_hash = "0x29cd80a097c7ae5ceace6867d6c0b5e31a6016944e067b8986b78f897108bf"
original_class_hash = "0x29cd80a097c7ae5ceace6867d6c0b5e31a6016944e067b8986b78f897108bf"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/blobbar_blobert_seeder_Seeder.json"
reads = []
writes = []
computed = []
name = "blobbar::blobert::seeder::Seeder"

[[contracts]]
kind = "DojoContract"
address = "0x3dd4f36c116335afd65dd8b8603c548101eb2bf476b971021528ba31f2f1f9c"
class_hash = "0x1c671d32a5938b013b0d99e2288b5ddb55a67369d7b37a7dd4d8a8b7552681e"
original_class_hash = "0x1c671d32a5938b013b0d99e2288b5ddb55a67369d7b37a7dd4d8a8b7552681e"
base_class_hash = "0x679177a2cb757694ac4f326d01052ff0963eac0bc2a17116a2b87badcdf6f76"
abi = "abis/deployments/contracts/blobbar_systems_actions_actions.json"
reads = []
writes = []
computed = []
name = "blobbar::systems::actions::actions"

[[models]]
kind = "DojoModel"
class_hash = "0x60ae977c28eaf251905cb160bfd50962a979b950d2afae844f6102d1d506d72"
original_class_hash = "0x60ae977c28eaf251905cb160bfd50962a979b950d2afae844f6102d1d506d72"
abi = "abis/deployments/models/blobbar_models_addresses_addresses.json"
name = "blobbar::models::addresses::addresses"

[[models.members]]
name = "key"
type = "u8"
key = true

[[models.members]]
name = "seeder"
type = "ContractAddress"
key = false

[[models.members]]
name = "descriptor"
type = "ContractAddress"
key = false

[[models.members]]
name = "set"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x81f51de83467639dfe38bb57db63fff3b91220591894405514e92c2d9d7a0a"
original_class_hash = "0x81f51de83467639dfe38bb57db63fff3b91220591894405514e92c2d9d7a0a"
abi = "abis/deployments/models/blobbar_models_blobtender_blobtender.json"
name = "blobbar::models::blobtender::blobtender"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "level"
type = "Level"
key = false

[[models.members]]
name = "position"
type = "Vec2"
key = false

[[models.members]]
name = "serving"
type = "DrinkType"
key = false

[[models.members]]
name = "clients_served"
type = "u32"
key = false

[[models.members]]
name = "high_score"
type = "u32"
key = false

[[models.members]]
name = "blobert"
type = "Seed"
key = false

[[models.members]]
name = "start_time"
type = "u64"
key = false
